<?php

use Phinx\Seed\AbstractSeed;

class CustomElementsSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $data = array(
            array(
                'id' => 1,
                'name' => 'Strona główna: Box glówny',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'id' => 2,
                'name' => 'Strona główna: kim jestesmy',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'id' => 3,
                'name' => 'Strona glowna: opis prawy',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'id' => 4,
                'name' => 'Strona glówna: produkty z zakladkami',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'id' => 5,
                'name' => 'Strona glówna: aktualnosci na glownej',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'id' => 6,
                'name' => 'Strona glówna: box dolny',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'id' => 7,
                'name' => 'Stopka',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'id' => 0,
                'name' => 'Strony: zdjécia',
                'created_at' => date('Y-m-d H:i:s'),
            )
        );

        $this->table('duo_custom_elements')->insert($data)->save();

        $data = array(
            array(
                'custom_element_id' => 1,
                'lang' => 'pl',
                'title' => 'Slogan1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'de',
                'title' => 'Slogan1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'en',
                'title' => 'Slogan1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'ru',
                'title' => 'Slogan1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'pl',
                'title' => 'Slogan2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'de',
                'title' => 'Slogan2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'en',
                'title' => 'Slogan2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'ru',
                'title' => 'Slogan2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'pl',
                'title' => 'url',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'de',
                'title' => 'url',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'en',
                'title' => 'url',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'ru',
                'title' => 'url',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'pl',
                'title' => 'Zdjecie 1',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'pl',
                'title' => 'Zdjecie 2',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'pl',
                'title' => 'Zdjecie 3',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'pl',
                'title' => 'Zdjecie 4',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'pl',
                'title' => 'Zdjecie 5',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 1,
                'lang' => 'pl',
                'title' => 'Zdjecie 6',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'pl',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'de',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'en',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'ru',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'pl',
                'title' => 'Tekst',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'de',
                'title' => 'Tekst',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'en',
                'title' => 'Tekst',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'ru',
                'title' => 'Tekst',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'pl',
                'title' => 'Link',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'de',
                'title' => 'Link',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'en',
                'title' => 'Link',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 2,
                'lang' => 'ru',
                'title' => 'Link',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'pl',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'de',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'en',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),array(
                'custom_element_id' => 3,
                'lang' => 'ru',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'pl',
                'title' => 'Opis',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'de',
                'title' => 'Opis',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'en',
                'title' => 'Opis',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'ru',
                'title' => 'Opis',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'pl',
                'title' => 'Tytul 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'de',
                'title' => 'Tytul 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'en',
                'title' => 'Tytul 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'ru',
                'title' => 'Tytul 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'pl',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'de',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'en',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 3,
                'lang' => 'ru',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'Tytul 1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'Tytul 1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'Tytul 1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'Tytul 1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'Tytul 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'Tytul 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'Tytul 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'Tytul 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'Tytul 1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'Tytul 3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'Tytul 3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'Tytul 3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'Slogan 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'Slogan 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'Slogan 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'Slogan 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'Slogan 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'Slogan 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'Slogan 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'Slogan 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'Slogan 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'Slogan 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'Slogan 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'Slogan 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'Opis 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'Opis 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'Opis 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'Opis 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'Opis 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'Opis 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'Opis 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'Opis 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'obraz duzy 1',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'obraz duzy 1',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'obraz duzy 1',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'obraz duzy 1',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'obraz duzy 2',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'obraz duzy 2',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'obraz duzy 2',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'obraz duzy 2',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'obraz duzy 3',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'obraz duzy 3',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'obraz duzy 3',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'obraz duzy 3',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'obraz maly 1',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'obraz maly 1',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'obraz maly 1',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'obraz maly 1',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
             array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'obraz maly 2',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'obraz maly 2',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'obraz maly 2',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'obraz maly 2',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
             array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'obraz maly 3',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'obraz maly 3',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'obraz maly 3',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'obraz maly 3',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'link1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'link1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'link1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'link1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'link2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'link2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'link2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'link2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'pl',
                'title' => 'link3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'ru',
                'title' => 'link3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'de',
                'title' => 'link3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 4,
                'lang' => 'en',
                'title' => 'link3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'obraz 1',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'obraz 2',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'obraz 3',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'data 1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'data 1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'data 1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'data 1',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'data 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'data 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'data 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'data 2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'data 3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'data 3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'data 3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'data 3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'Tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'Tytul2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'Tytul2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'Tytul2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'Tytul2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'Tytul3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'Tytul3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'Tytul3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'Tytul3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),  
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'Opis 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'Opis 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'Opis 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'Opis 1',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'Opis 2',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'Opis 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'Opis 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'Opis 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'Opis 3',
                'type' => 'ckeditor',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'link',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'link',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'link',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'link',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'link2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'link2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'link2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'link2',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'pl',
                'title' => 'link3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'de',
                'title' => 'link3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'en',
                'title' => 'link3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 5,
                'lang' => 'ru',
                'title' => 'link3',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 6,
                'lang' => 'pl',
                'title' => 'Gdzie kupic',
                'type' => 'text',
                'value' => 'Gdzie kupic',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 6,
                'lang' => 'de',
                'title' => 'Gdzie kupic',
                'type' => 'text',
                'value' => 'Gdzie kupic',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 6,
                'lang' => 'en',
                'title' => 'Gdzie kupic',
                'type' => 'text',
                'value' => 'Gdzie kupic',
                'created_at' => date('Y-m-d H:i:s'),
            ),array(
                'custom_element_id' => 6,
                'lang' => 'ru',
                'title' => 'Gdzie kupic',
                'type' => 'text',
                'value' => 'Gdzie kupic',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 6,
                'lang' => 'pl',
                'title' => 'Obraz 1',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 6,
                'lang' => 'pl',
                'title' => 'Obraz 2',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 6,
                'lang' => 'pl',
                'title' => 'Kontakt tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 6,
                'lang' => 'de',
                'title' => 'Kontakt tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 6,
                'lang' => 'en',
                'title' => 'Kontakt tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 6,
                'lang' => 'ru',
                'title' => 'Kontakt tytul',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 7,
                'lang' => 'pl',
                'title' => 'Stopka',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 7,
                'lang' => 'de',
                'title' => 'Stopka',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 7,
                'lang' => 'en',
                'title' => 'Stopka',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 7,
                'lang' => 'ru',
                'title' => 'Stopka',
                'type' => 'text',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            ),
            array(
                'custom_element_id' => 8,
                'lang' => 'pl',
                'title' => 'O firmie',
                'type' => 'image',
                'value' => '',
                'created_at' => date('Y-m-d H:i:s'),
            )
        );

        $this->table('duo_custom_element_fields')->insert($data)->save();
    }
}
